#ifndef LOCALSTORAGE_GLOBAL_H
#define LOCALSTORAGE_GLOBAL_H

#include <QtCore/qglobal.h>

#define INSERT_FRINED 0
#define INSERT_GROUP  1
#define INSERT_FEED   2
#define INSERT_MYSTUFF 3
#define INSERT_COLLEAGUERELATION 4
#define INSERT_COLLEAGUEGROUP 5
#define INSERT_MYGROUP 6
#define INSERT_GROUPINFO 7
#define INSERT_GROUPMEMBER 8
#define INSERT_COMPANY   9
#define INSERT_NEWFRIEND 10
#define INSERT_COMMON_FACEID 11


#ifdef LOCALSTORAGE_LIB
# define LOCALSTORAGE_EXPORT Q_DECL_EXPORT
#else
# define LOCALSTORAGE_EXPORT Q_DECL_IMPORT
#endif

#endif // LOCALSTORAGE_GLOBAL_H
