# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.


HEADERS += ./CardCase.h \
    ./cardcase_global.h \
    ./stdafx.h \
    ./CardCaseListArea.h
SOURCES += ./CardCase.cpp \
    ./CardCaseListArea.cpp \
    ./stdafx.cpp
RESOURCES += CardCase.qrc
